### ISSUE TITLE
When will you open source the code?

### ISSUE THREAD

**Issue by YoucanBaby** [yihuacheng/DVGaze#1]
Hi, thank you for your perfect work~. When will you open source the code?

**Comment by yihuacheng** [comment]
Thanks for your attention on our work.

I am having a busy trip and will attend the ICCV conference.

I have released a beta version of our work. You can download and conduct new research based on it.

If you have any questions, please contact me at y.cheng.2@bham.ac.uk.

Best wishes,
Yihua, Sep. 27.
